spring:
  datasource:
    url: jdbc:mysql://localhost:3306/game?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: game
    password: 123456
  #mongo配置
  data:
    mongodb:
      database: game_db
      uri: mongodb://39.104.127.153:28018
  redis:
    host: localhost
    port: 6379